# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 353)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 80, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 61, 16))
        self.label_2.setObjectName("label_2")
        self.studentNameInput = QtWidgets.QLineEdit(Form)
        self.studentNameInput.setGeometry(QtCore.QRect(150, 80, 113, 20))
        self.studentNameInput.setText("")
        self.studentNameInput.setObjectName("studentNameInput")
        self.studentIdInput = QtWidgets.QLineEdit(Form)
        self.studentIdInput.setGeometry(QtCore.QRect(150, 120, 113, 20))
        self.studentIdInput.setObjectName("studentIdInput")
        self.generateButton = QtWidgets.QPushButton(Form)
        self.generateButton.setGeometry(QtCore.QRect(150, 160, 75, 23))
        self.generateButton.setObjectName("generateButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 210, 61, 16))
        self.label_3.setObjectName("label_3")
        self.login = QtWidgets.QLineEdit(Form)
        self.login.setGeometry(QtCore.QRect(140, 210, 113, 20))
        self.login.setReadOnly(True)
        self.login.setObjectName("login")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 250, 47, 13))
        self.label_4.setObjectName("label_4")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(140, 250, 113, 20))
        self.password.setReadOnly(False)
        self.password.setObjectName("password")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "student_name"))
        self.label_2.setText(_translate("Form", "student_ID"))
        self.studentNameInput.setPlaceholderText(_translate("Form", "enter your name"))
        self.studentIdInput.setPlaceholderText(_translate("Form", "enter your ID"))
        self.generateButton.setText(_translate("Form", "Generate "))
        self.label_3.setText(_translate("Form", "login"))
        self.label_4.setText(_translate("Form", "password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
